- hosts: haproxy*
  sudo: yes
  roles:
    - { role: geerlingguy.haproxy }
  vars:
    haproxy_global_vars:
      - 'maxconn 2000'
      - 'ulimit-n 16384'
      - 'log 127.0.0.1 local0 err'
      - 'stats timeout 30s'
      
    haproxy_frontend_name: 'k8s-api'
    haproxy_frontend_bind_address: '*'
    haproxy_frontend_port: '8443'
    haproxy_frontend_mode: 'tcp'
    
    haproxy_backend_name: 'k8s-api'
    haproxy_backend_mode: 'tcp'
    haproxy_backend_balance_method: 'roundrobin'
    haproxy_backend_httpchk: 'GET /healthz'
    haproxy_backend_servers:
      - name: m1
        address: k8s-m1:6443
      - name: m2
        address: k8s-m2:6443
      - name: m3
        address: k8s-m3:6443
