---
- hosts: k8s-cluster
  become: True
  gather_facts: True
  tasks:
    - name: Make sure group wheel is not in the sudoers configuration
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^172.16'

    - name: Update the /etc/hosts file with node name
      tags: etchostsupdate
      become: yes
      become_user: root
      lineinfile:
        path: "/etc/hosts"
        regexp: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        state: present
        backup: yes
      register: etchostsupdate
      when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
      with_items: "{{ansible_play_hosts}}"

    - name: Disable swap 
      shell: swapoff -a
    
    # Another method :https://github.com/djx339/ansible-role-swapoff/blob/master/tasks/main.yml
    - name: Disable swap permanently 
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '(?i)^(/dev/mapper/centos-swap.*)'
        line: '# \1'
        backrefs: yes
        state: present

    - name: Disable permanently stop firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
        daemon_reload: yes
  
